# Generated by Django 3.1 on 2020-09-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ability',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='test',
            name='age',
            field=models.DecimalField(decimal_places=5, default='', max_digits=9),
        ),
        migrations.AddField(
            model_name='test',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
