# Generated by Django 3.1 on 2020-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200905_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
        migrations.AlterField(
            model_name='test',
            name='ability',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='test',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
