# Generated by Django 3.1 on 2020-09-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200905_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='pony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('ability', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='test',
            name='color',
        ),
    ]
