# Generated by Django 3.1 on 2020-09-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200905_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
